// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\5"+
    "\1\6\1\0\1\7\2\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\11\1\10\1\35\1\36\1\37\2\10\1\40\1\41"+
    "\1\42\1\43\1\44\1\40\1\45\4\40\1\46\5\40"+
    "\1\47\10\40\4\0\1\50\1\0\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\40\1\60\2\40\1\61"+
    "\1\62\1\63\1\64\1\65\1\40\1\66\1\67\1\70"+
    "\1\71\1\72\1\40\1\73\1\74\1\40\1\75\1\10"+
    "\1\76\7\0\1\3\33\0\1\10\12\0\1\10\22\0"+
    "\1\10\u0168\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\2\22\1\23\20\22\1\24\1\25"+
    "\2\2\1\5\3\0\1\26\1\27\15\22\1\30\5\22"+
    "\1\31\10\22\3\2\1\32\1\0\1\33\1\34\1\35"+
    "\1\36\14\22\1\37\3\22\1\40\13\22\1\41\1\2"+
    "\3\0\3\22\1\42\5\22\1\43\2\22\1\44\1\22"+
    "\1\45\12\22\1\46\1\47\1\0\1\50\3\22\1\51"+
    "\2\22\1\52\1\22\1\53\1\22\1\54\1\22\1\0"+
    "\1\55\3\22\1\56\1\57\2\22\1\0\1\22\1\60"+
    "\2\22\1\61\3\22\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\1\70\1\71\1\72\2\22\1\73\1\74\1\22"+
    "\1\75\1\76\1\77\1\100\4\22\1\101\1\22\1\102"+
    "\1\103\3\22\1\104\1\105\2\22\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\77\0\176\0\77\0\275\0\374\0\u013b"+
    "\0\77\0\77\0\77\0\77\0\77\0\77\0\77\0\u017a"+
    "\0\u01b9\0\u01f8\0\77\0\u0237\0\u0276\0\u02b5\0\u02f4\0\u0333"+
    "\0\u0372\0\u03b1\0\u03f0\0\u042f\0\u046e\0\u04ad\0\u04ec\0\u052b"+
    "\0\u056a\0\u05a9\0\u05e8\0\u0627\0\u0666\0\u06a5\0\u06e4\0\77"+
    "\0\77\0\u0723\0\u0762\0\u07a1\0\u07e0\0\u081f\0\u085e\0\77"+
    "\0\77\0\u089d\0\u08dc\0\u091b\0\u095a\0\u0999\0\u09d8\0\u0a17"+
    "\0\u0a56\0\u0a95\0\u0ad4\0\u0b13\0\u0b52\0\u0b91\0\u0276\0\u0bd0"+
    "\0\u0c0f\0\u0c4e\0\u0c8d\0\u0ccc\0\u0276\0\u0d0b\0\u0d4a\0\u0d89"+
    "\0\u0dc8\0\u0e07\0\u0e46\0\u0e85\0\u0ec4\0\u0f03\0\u0f42\0\u0f81"+
    "\0\77\0\u0fc0\0\u085e\0\u0276\0\u0fff\0\u0276\0\u103e\0\u107d"+
    "\0\u10bc\0\u10fb\0\u113a\0\u1179\0\u11b8\0\u11f7\0\u1236\0\u1275"+
    "\0\u12b4\0\u12f3\0\u0276\0\u1332\0\u1371\0\u13b0\0\u0276\0\u13ef"+
    "\0\u142e\0\u146d\0\u14ac\0\u14eb\0\u152a\0\u1569\0\u15a8\0\u15e7"+
    "\0\u1626\0\u1665\0\u0276\0\u16a4\0\u0f42\0\u16e3\0\u1722\0\u1761"+
    "\0\u17a0\0\u17df\0\u0276\0\u181e\0\u185d\0\u189c\0\u18db\0\u191a"+
    "\0\u0276\0\u1959\0\u1998\0\u0276\0\u19d7\0\u0276\0\u1a16\0\u1a55"+
    "\0\u1a94\0\u1ad3\0\u1b12\0\u1b51\0\u1b90\0\u1bcf\0\u1c0e\0\u1c4d"+
    "\0\u0276\0\u0276\0\u1c8c\0\u0276\0\u1ccb\0\u1d0a\0\u1d49\0\u0276"+
    "\0\u1d88\0\u1dc7\0\u0276\0\u1e06\0\u0276\0\u1e45\0\u0276\0\u1e84"+
    "\0\u1ec3\0\u0276\0\u1f02\0\u1f41\0\u1f80\0\u0276\0\u0276\0\u1fbf"+
    "\0\u1ffe\0\u203d\0\u207c\0\u0276\0\u20bb\0\u20fa\0\u0276\0\u2139"+
    "\0\u2178\0\u21b7\0\77\0\77\0\77\0\77\0\77\0\77"+
    "\0\77\0\77\0\77\0\u21f6\0\u2235\0\u0276\0\u0276\0\u2274"+
    "\0\77\0\u0276\0\u0276\0\u0276\0\u22b3\0\u22f2\0\u2331\0\u2370"+
    "\0\u0276\0\u23af\0\u0276\0\u0276\0\u23ee\0\u242d\0\u246c\0\u0276"+
    "\0\u0276\0\u24ab\0\u24ea\0\u0276";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\3\1\5\1\6\1\7"+
    "\1\2\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\12\21\1\22\1\23\1\24\6\25\1\26"+
    "\1\25\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\25\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\25\1\47\2\25\1\50\1\51\101\0"+
    "\1\3\74\0\2\52\1\3\1\52\1\4\10\52\1\53"+
    "\61\52\10\0\1\7\100\0\1\54\10\0\12\55\3\0"+
    "\10\55\1\0\24\55\17\0\1\56\102\0\1\57\1\0"+
    "\12\21\100\0\1\60\76\0\1\61\63\0\12\25\3\0"+
    "\10\25\1\0\24\25\25\0\12\25\3\0\2\25\1\62"+
    "\1\25\1\63\3\25\1\0\24\25\52\0\1\27\51\0"+
    "\12\25\3\0\10\25\1\0\12\25\1\64\11\25\25\0"+
    "\12\25\3\0\10\25\1\0\4\25\1\65\6\25\1\66"+
    "\4\25\1\67\3\25\25\0\12\25\3\0\10\25\1\0"+
    "\1\70\12\25\1\71\10\25\25\0\12\25\3\0\10\25"+
    "\1\0\4\25\1\72\2\25\1\73\14\25\25\0\12\25"+
    "\3\0\10\25\1\0\10\25\1\74\13\25\25\0\12\25"+
    "\3\0\10\25\1\0\1\75\17\25\1\76\3\25\25\0"+
    "\12\25\3\0\10\25\1\0\5\25\1\77\4\25\1\100"+
    "\11\25\25\0\12\25\3\0\10\25\1\0\13\25\1\101"+
    "\10\25\25\0\12\25\3\0\10\25\1\0\13\25\1\102"+
    "\10\25\25\0\12\25\3\0\10\25\1\0\13\25\1\103"+
    "\10\25\25\0\12\25\3\0\10\25\1\0\14\25\1\104"+
    "\1\105\6\25\25\0\12\25\3\0\10\25\1\0\13\25"+
    "\1\106\1\25\1\107\6\25\25\0\12\25\3\0\10\25"+
    "\1\0\4\25\1\110\17\25\25\0\12\25\3\0\10\25"+
    "\1\0\17\25\1\111\4\25\25\0\12\25\3\0\10\25"+
    "\1\0\4\25\1\112\2\25\1\113\5\25\1\114\6\25"+
    "\25\0\12\25\3\0\10\25\1\0\1\115\23\25\2\0"+
    "\2\52\1\3\1\52\1\4\72\52\2\116\1\117\1\116"+
    "\1\120\10\116\1\52\61\116\12\0\1\54\71\0\1\55"+
    "\1\0\1\55\1\0\1\55\1\121\2\55\1\0\61\55"+
    "\15\0\1\122\104\0\12\123\65\0\12\25\3\0\3\25"+
    "\1\124\4\25\1\0\24\25\25\0\12\25\3\0\3\25"+
    "\1\125\4\25\1\0\24\25\25\0\12\25\3\0\10\25"+
    "\1\0\3\25\1\126\20\25\25\0\12\25\3\0\10\25"+
    "\1\0\6\25\1\127\15\25\25\0\12\25\3\0\10\25"+
    "\1\0\13\25\1\130\10\25\25\0\12\25\3\0\10\25"+
    "\1\0\17\25\1\131\4\25\25\0\12\25\3\0\10\25"+
    "\1\0\10\25\1\132\13\25\25\0\12\25\3\0\10\25"+
    "\1\0\12\25\1\133\11\25\25\0\12\25\3\0\10\25"+
    "\1\0\2\25\1\134\3\25\1\135\1\25\1\136\13\25"+
    "\25\0\12\25\3\0\10\25\1\0\16\25\1\137\5\25"+
    "\25\0\12\25\3\0\10\25\1\0\16\25\1\140\5\25"+
    "\25\0\12\25\3\0\10\25\1\0\10\25\1\141\13\25"+
    "\25\0\12\25\3\0\10\25\1\0\12\25\1\142\11\25"+
    "\25\0\12\25\3\0\10\25\1\0\17\25\1\143\4\25"+
    "\25\0\12\25\3\0\10\25\1\0\13\25\1\144\10\25"+
    "\25\0\12\25\3\0\10\25\1\0\17\25\1\145\1\25"+
    "\1\146\2\25\25\0\12\25\3\0\10\25\1\0\17\25"+
    "\1\147\4\25\25\0\12\25\3\0\10\25\1\0\4\25"+
    "\1\150\17\25\25\0\12\25\3\0\10\25\1\0\15\25"+
    "\1\151\6\25\25\0\12\25\3\0\10\25\1\0\7\25"+
    "\1\152\3\25\1\153\10\25\25\0\12\25\3\0\10\25"+
    "\1\0\16\25\1\154\1\155\4\25\25\0\12\25\3\0"+
    "\10\25\1\0\1\156\14\25\1\157\6\25\25\0\12\25"+
    "\3\0\10\25\1\0\11\25\1\160\12\25\25\0\12\25"+
    "\3\0\10\25\1\0\11\25\1\161\12\25\25\0\12\25"+
    "\3\0\10\25\1\0\20\25\1\162\3\25\25\0\12\25"+
    "\3\0\10\25\1\0\15\25\1\163\6\25\2\0\2\116"+
    "\1\117\1\116\1\120\10\116\1\164\61\116\15\165\1\166"+
    "\63\165\1\117\12\165\1\166\61\165\15\0\1\122\4\0"+
    "\1\3\77\0\12\25\3\0\10\25\1\167\24\25\25\0"+
    "\12\25\3\0\10\25\1\0\7\25\1\170\14\25\25\0"+
    "\12\25\3\0\10\25\1\0\10\25\1\171\13\25\25\0"+
    "\12\25\3\0\10\25\1\0\17\25\1\172\4\25\25\0"+
    "\12\25\3\0\10\25\1\0\10\25\1\173\13\25\25\0"+
    "\12\25\3\0\10\25\1\0\16\25\1\174\5\25\25\0"+
    "\12\25\3\0\10\25\1\0\7\25\1\175\14\25\25\0"+
    "\12\25\3\0\10\25\1\0\15\25\1\176\6\25\25\0"+
    "\12\25\3\0\10\25\1\0\1\177\23\25\25\0\12\25"+
    "\3\0\10\25\1\0\17\25\1\200\4\25\25\0\12\25"+
    "\3\0\10\25\1\0\4\25\1\201\17\25\25\0\12\25"+
    "\3\0\10\25\1\0\16\25\1\202\5\25\25\0\12\25"+
    "\3\0\10\25\1\0\2\25\1\203\21\25\25\0\12\25"+
    "\3\0\10\25\1\0\14\25\1\204\7\25\25\0\12\25"+
    "\3\0\10\25\1\0\13\25\1\205\10\25\25\0\12\25"+
    "\3\0\10\25\1\0\4\25\1\206\17\25\25\0\12\25"+
    "\3\0\10\25\1\0\15\25\1\207\6\25\25\0\12\25"+
    "\3\0\10\25\1\0\17\25\1\210\4\25\25\0\12\25"+
    "\3\0\10\25\1\0\12\25\1\211\11\25\25\0\12\25"+
    "\3\0\10\25\1\0\22\25\1\212\1\25\25\0\12\25"+
    "\3\0\10\25\1\0\17\25\1\213\4\25\25\0\12\25"+
    "\3\0\10\25\1\0\20\25\1\214\3\25\25\0\12\25"+
    "\3\0\10\25\1\0\15\25\1\215\1\25\1\216\4\25"+
    "\25\0\12\25\3\0\10\25\1\0\7\25\1\217\14\25"+
    "\25\0\12\25\3\0\10\25\1\0\14\25\1\220\7\25"+
    "\25\0\12\25\3\0\10\25\1\0\4\25\1\221\17\25"+
    "\25\0\12\25\3\0\10\25\1\0\4\25\1\222\17\25"+
    "\2\0\2\116\1\117\1\116\1\120\10\116\1\164\4\116"+
    "\1\52\54\116\15\165\1\166\4\165\1\3\54\165\47\0"+
    "\1\223\52\0\12\25\3\0\10\25\1\0\12\25\1\224"+
    "\11\25\25\0\12\25\3\0\10\25\1\0\4\25\1\225"+
    "\17\25\25\0\12\25\3\0\10\25\1\0\13\25\1\226"+
    "\10\25\25\0\12\25\3\0\10\25\1\0\13\25\1\227"+
    "\3\25\1\230\4\25\25\0\12\25\3\0\10\25\1\0"+
    "\11\25\1\231\12\25\25\0\12\25\3\0\10\25\1\0"+
    "\4\25\1\232\17\25\25\0\12\25\3\0\10\25\1\0"+
    "\23\25\1\233\25\0\12\25\3\0\10\25\1\0\1\234"+
    "\23\25\25\0\12\25\3\0\10\25\1\0\4\25\1\235"+
    "\17\25\25\0\12\25\3\0\10\25\1\0\17\25\1\236"+
    "\4\25\25\0\12\25\3\0\10\25\1\0\15\25\1\237"+
    "\6\25\25\0\12\25\3\0\10\25\1\0\1\240\23\25"+
    "\25\0\12\25\3\0\10\25\1\241\24\25\25\0\12\25"+
    "\3\0\10\25\1\0\17\25\1\242\4\25\25\0\12\25"+
    "\3\0\10\25\1\0\7\25\1\243\14\25\25\0\12\25"+
    "\3\0\10\25\1\0\1\244\23\25\25\0\12\25\3\0"+
    "\10\25\1\0\15\25\1\245\6\25\25\0\12\25\3\0"+
    "\10\25\1\0\17\25\1\246\4\25\25\0\12\25\3\0"+
    "\10\25\1\0\4\25\1\247\17\25\25\0\12\25\3\0"+
    "\10\25\1\0\12\25\1\250\11\25\25\0\12\25\3\0"+
    "\10\25\1\0\4\25\1\251\17\25\47\0\1\252\54\0"+
    "\12\25\3\0\10\25\1\0\1\253\23\25\25\0\12\25"+
    "\3\0\10\25\1\0\12\25\1\254\11\25\25\0\12\25"+
    "\3\0\10\25\1\0\10\25\1\255\13\25\25\0\12\25"+
    "\3\0\10\25\1\0\1\256\23\25\25\0\12\25\3\0"+
    "\10\25\1\0\4\25\1\257\17\25\25\0\12\25\3\0"+
    "\10\25\1\0\12\25\1\260\11\25\25\0\12\25\3\0"+
    "\10\25\1\0\7\25\1\261\14\25\25\0\12\25\3\0"+
    "\10\25\1\0\17\25\1\262\4\25\26\0\1\263\1\264"+
    "\1\265\1\266\1\267\1\270\1\271\1\272\1\273\65\0"+
    "\12\25\3\0\10\25\1\0\11\25\1\274\12\25\25\0"+
    "\12\25\3\0\10\25\1\0\15\25\1\275\6\25\25\0"+
    "\12\25\3\0\10\25\1\0\12\25\1\276\11\25\25\0"+
    "\12\25\3\0\10\25\1\0\6\25\1\277\15\25\25\0"+
    "\12\25\3\0\10\25\1\0\15\25\1\300\6\25\43\0"+
    "\1\301\60\0\12\25\3\0\10\25\1\0\12\25\1\302"+
    "\11\25\25\0\12\25\3\0\10\25\1\0\4\25\1\303"+
    "\17\25\25\0\12\25\3\0\10\25\1\0\10\25\1\304"+
    "\13\25\25\0\12\25\3\0\10\25\1\0\2\25\1\305"+
    "\21\25\25\0\12\25\3\0\10\25\1\0\13\25\1\306"+
    "\10\25\25\0\12\25\3\0\10\25\1\0\7\25\1\307"+
    "\14\25\25\0\12\25\3\0\10\25\1\0\7\25\1\310"+
    "\14\25\25\0\12\25\3\0\10\25\1\0\17\25\1\311"+
    "\4\25\25\0\12\25\3\0\10\25\1\0\1\312\23\25"+
    "\25\0\12\25\3\0\10\25\1\0\4\25\1\313\17\25"+
    "\25\0\12\25\3\0\10\25\1\0\12\25\1\314\11\25"+
    "\25\0\12\25\3\0\10\25\1\0\13\25\1\315\10\25"+
    "\25\0\12\25\3\0\10\25\1\0\17\25\1\316\4\25"+
    "\25\0\12\25\3\0\10\25\1\0\17\25\1\317\4\25"+
    "\25\0\12\25\3\0\10\25\1\0\12\25\1\320\11\25"+
    "\25\0\12\25\3\0\10\25\1\0\23\25\1\321\25\0"+
    "\12\25\3\0\10\25\1\0\20\25\1\322\3\25\25\0"+
    "\12\25\3\0\10\25\1\0\15\25\1\323\6\25\25\0"+
    "\12\25\3\0\10\25\1\0\4\25\1\324\17\25\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9513];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\3\1\7\11\3\1\1\11"+
    "\24\1\2\11\3\1\3\0\2\11\37\1\1\11\1\0"+
    "\42\1\3\0\33\1\1\0\15\1\1\0\10\1\1\0"+
    "\10\1\11\11\5\1\1\11\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR_X", yyline, yycolumn);
            }
            // fall through
          case 71: break;
          case 2:
            { /*Ignorar*/
            }
            // fall through
          case 72: break;
          case 3:
            { return token(yytext(), "FIN_DE_LINEA", yyline, yycolumn);
            }
            // fall through
          case 73: break;
          case 4:
            { return token(yytext(), "ERROR_0", yyline, yycolumn);
            }
            // fall through
          case 74: break;
          case 5:
            { return token(yytext(), "ERROR_1", yyline, yycolumn);
            }
            // fall through
          case 75: break;
          case 6:
            { return token(yytext(), "L_PARENT", yyline, yycolumn);
            }
            // fall through
          case 76: break;
          case 7:
            { return token(yytext(), "R_PARENT", yyline, yycolumn);
            }
            // fall through
          case 77: break;
          case 8:
            { return token(yytext(), "OP_ARITMETICO_MULTI", yyline, yycolumn);
            }
            // fall through
          case 78: break;
          case 9:
            { return token(yytext(), "OP_ARITMETICO_SUMA", yyline, yycolumn);
            }
            // fall through
          case 79: break;
          case 10:
            { return token(yytext(), "SIGNO_PUNTUACION_COMA", yyline, yycolumn);
            }
            // fall through
          case 80: break;
          case 11:
            { return token(yytext(), "OP_ARITMETICO_RESTA", yyline, yycolumn);
            }
            // fall through
          case 81: break;
          case 12:
            { return token(yytext(), "SIGNO_PUNTUACION_PUNTO", yyline, yycolumn);
            }
            // fall through
          case 82: break;
          case 13:
            { return token(yytext(), "OP_ARITMETICO_DIV", yyline, yycolumn);
            }
            // fall through
          case 83: break;
          case 14:
            { return token(yytext(), "VALOR_NUMERO_ENTERO", yyline, yycolumn);
            }
            // fall through
          case 84: break;
          case 15:
            { return token(yytext(), "OP_RELACIONAL_MENOR_QUE", yyline, yycolumn);
            }
            // fall through
          case 85: break;
          case 16:
            { return token(yytext(), "OP_ASIGNACION", yyline, yycolumn);
            }
            // fall through
          case 86: break;
          case 17:
            { return token(yytext(), "OP_RELACIONAL_MAYOR_QUE", yyline, yycolumn);
            }
            // fall through
          case 87: break;
          case 18:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
            }
            // fall through
          case 88: break;
          case 19:
            { return token(yytext(), "ERROR_2", yyline, yycolumn);
            }
            // fall through
          case 89: break;
          case 20:
            { return token(yytext(), "L_LLAVE", yyline, yycolumn);
            }
            // fall through
          case 90: break;
          case 21:
            { return token(yytext(), "R_LLAVE", yyline, yycolumn);
            }
            // fall through
          case 91: break;
          case 22:
            { return token(yytext(), "OP_RELACIONAL_MENOR_IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 92: break;
          case 23:
            { return token(yytext(), "OP_RELACIONAL_MAYOR_IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 93: break;
          case 24:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_I", yyline, yycolumn);
            }
            // fall through
          case 94: break;
          case 25:
            { return token(yytext(), "OP_LOGICO_OR", yyline, yycolumn);
            }
            // fall through
          case 95: break;
          case 26:
            { return token(yytext(), "VALOR_CADENA", yyline, yycolumn);
            }
            // fall through
          case 96: break;
          case 27:
            { return token(yytext(), "VALOR_NUMERO_REAL", yyline, yycolumn);
            }
            // fall through
          case 97: break;
          case 28:
            { return token(yytext(), "TIPO_PUERTO_LCD", yyline, yycolumn);
            }
            // fall through
          case 98: break;
          case 29:
            { return token(yytext(), "TIPO_PUERTO_LED", yyline, yycolumn);
            }
            // fall through
          case 99: break;
          case 30:
            { return token(yytext(), "OP_LOGICO_AND", yyline, yycolumn);
            }
            // fall through
          case 100: break;
          case 31:
            { return token(yytext(), "TIPO_DATO_I", yyline, yycolumn);
            }
            // fall through
          case 101: break;
          case 32:
            { return token(yytext(), "OP_LOGICO_NOT", yyline, yycolumn);
            }
            // fall through
          case 102: break;
          case 33:
            { return token(yytext(), "DECLARACION_V", yyline, yycolumn);
            }
            // fall through
          case 103: break;
          case 34:
            { return token(yytext(), "METODO_CALL", yyline, yycolumn);
            }
            // fall through
          case 104: break;
          case 35:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_E", yyline, yycolumn);
            }
            // fall through
          case 105: break;
          case 36:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_L", yyline, yycolumn);
            }
            // fall through
          case 106: break;
          case 37:
            { return token(yytext(), "MOTOR_M", yyline, yycolumn);
            }
            // fall through
          case 107: break;
          case 38:
            { return token(yytext(), "METODO_SENSOR_TIME", yyline, yycolumn);
            }
            // fall through
          case 108: break;
          case 39:
            { return token(yytext(), "VALOR_CONDICIONAL_T", yyline, yycolumn);
            }
            // fall through
          case 109: break;
          case 40:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_B", yyline, yycolumn);
            }
            // fall through
          case 110: break;
          case 41:
            { return token(yytext(), "DECLARACION_C", yyline, yycolumn);
            }
            // fall through
          case 111: break;
          case 42:
            { return token(yytext(), "METODO_D", yyline, yycolumn);
            }
            // fall through
          case 112: break;
          case 43:
            { return token(yytext(), "VALOR_CONDICIONAL_F", yyline, yycolumn);
            }
            // fall through
          case 113: break;
          case 44:
            { return token(yytext(), "TIPO_PUERTO_MOTOR", yyline, yycolumn);
            }
            // fall through
          case 114: break;
          case 45:
            { return token(yytext(), "METODO_P", yyline, yycolumn);
            }
            // fall through
          case 115: break;
          case 46:
            { return token(yytext(), "MOTOR_S", yyline, yycolumn);
            }
            // fall through
          case 116: break;
          case 47:
            { return token(yytext(), "METODO_SENSOR_STATE", yyline, yycolumn);
            }
            // fall through
          case 117: break;
          case 48:
            { return token(yytext(), "TIPO_PUERTO_BUTTON", yyline, yycolumn);
            }
            // fall through
          case 118: break;
          case 49:
            { return token(yytext(), "METODO_SENSOR_DEGREE", yyline, yycolumn);
            }
            // fall through
          case 119: break;
          case 50:
            { return token(yytext(), "PUERTO_1", yyline, yycolumn);
            }
            // fall through
          case 120: break;
          case 51:
            { return token(yytext(), "PUERTO_2", yyline, yycolumn);
            }
            // fall through
          case 121: break;
          case 52:
            { return token(yytext(), "PUERTO_3", yyline, yycolumn);
            }
            // fall through
          case 122: break;
          case 53:
            { return token(yytext(), "PUERTO_4", yyline, yycolumn);
            }
            // fall through
          case 123: break;
          case 54:
            { return token(yytext(), "PUERTO_5", yyline, yycolumn);
            }
            // fall through
          case 124: break;
          case 55:
            { return token(yytext(), "PUERTO_6", yyline, yycolumn);
            }
            // fall through
          case 125: break;
          case 56:
            { return token(yytext(), "PUERTO_7", yyline, yycolumn);
            }
            // fall through
          case 126: break;
          case 57:
            { return token(yytext(), "PUERTO_8", yyline, yycolumn);
            }
            // fall through
          case 127: break;
          case 58:
            { return token(yytext(), "PUERTO_9", yyline, yycolumn);
            }
            // fall through
          case 128: break;
          case 59:
            { return token(yytext(), "METODO_R", yyline, yycolumn);
            }
            // fall through
          case 129: break;
          case 60:
            { return token(yytext(), "TIPO_DATO_S", yyline, yycolumn);
            }
            // fall through
          case 130: break;
          case 61:
            { return token(yytext(), "TIPO_PUERTO_LED_RGB", yyline, yycolumn);
            }
            // fall through
          case 131: break;
          case 62:
            { return token(yytext(), "TIPO_DATO_B", yyline, yycolumn);
            }
            // fall through
          case 132: break;
          case 63:
            { return token(yytext(), "METODO_C", yyline, yycolumn);
            }
            // fall through
          case 133: break;
          case 64:
            { return token(yytext(), "TIPO_DATO_D", yyline, yycolumn);
            }
            // fall through
          case 134: break;
          case 65:
            { return token(yytext(), "MOTOR_R", yyline, yycolumn);
            }
            // fall through
          case 135: break;
          case 66:
            { return token(yytext(), "METODO_SENSOR_DISTANCE", yyline, yycolumn);
            }
            // fall through
          case 136: break;
          case 67:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_F", yyline, yycolumn);
            }
            // fall through
          case 137: break;
          case 68:
            { return token(yytext(), "METODO_O", yyline, yycolumn);
            }
            // fall through
          case 138: break;
          case 69:
            { return token(yytext(), "TIPO_PUERTO_PROXIMITY", yyline, yycolumn);
            }
            // fall through
          case 139: break;
          case 70:
            { return token(yytext(), "TIPO_PUERTO_TEMPERATURE", yyline, yycolumn);
            }
            // fall through
          case 140: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
