// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\5"+
    "\1\6\1\0\1\7\2\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\2\33\1\11"+
    "\1\10\1\34\1\35\1\36\2\10\1\37\1\40\1\41"+
    "\1\42\1\43\6\44\1\45\16\44\4\0\1\46\1\0"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\2\44\1\60\1\61\1\62\1\63\1\64\1\44"+
    "\1\65\1\66\1\67\1\70\1\71\1\44\1\72\1\73"+
    "\1\44\1\74\1\10\1\75\7\0\1\3\33\0\1\10"+
    "\12\0\1\10\22\0\1\10\u0168\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\2\22\1\23\20\22\1\24\1\25"+
    "\2\2\2\0\1\26\2\0\1\27\1\0\1\30\1\31"+
    "\1\32\1\33\1\34\15\22\1\35\6\22\1\36\11\22"+
    "\3\2\1\26\1\37\1\5\1\40\1\41\1\0\1\30"+
    "\1\42\1\43\1\44\1\45\14\22\1\46\4\22\1\47"+
    "\14\22\1\50\1\2\2\0\1\51\3\22\1\52\5\22"+
    "\1\53\3\22\1\54\1\22\1\55\12\22\1\56\1\57"+
    "\1\22\1\60\3\22\1\61\2\22\1\62\1\22\1\63"+
    "\2\22\1\64\1\22\1\0\1\65\3\22\1\66\1\67"+
    "\2\22\1\0\1\22\1\70\2\22\1\71\4\22\4\0"+
    "\2\22\1\72\1\73\1\22\1\0\1\74\1\75\1\76"+
    "\2\22\1\77\1\22\1\100\1\101\1\102\1\103\1\104"+
    "\1\105\1\106\1\107\1\110\1\111\1\112\1\113\1\114"+
    "\1\115\1\116\1\117\1\120\1\121\1\122\1\123\1\124"+
    "\1\125\1\126\1\127\1\130\1\131\1\132\1\133\1\22"+
    "\1\134\1\22\1\0\1\135\1\136\3\22\1\137\1\140"+
    "\1\141\2\22\1\142";

  private static int [] zzUnpackAction() {
    int [] result = new int[256];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\76\0\174\0\76\0\272\0\370\0\u0136"+
    "\0\76\0\76\0\76\0\76\0\76\0\76\0\u0174\0\u01b2"+
    "\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2"+
    "\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\u0554\0\u0592"+
    "\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706\0\u0744\0\76"+
    "\0\76\0\u0782\0\u07c0\0\u07fe\0\u083c\0\u087a\0\u08b8\0\u0174"+
    "\0\u08f6\0\u0934\0\u0972\0\u09b0\0\76\0\76\0\76\0\u09ee"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde"+
    "\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u02e8\0\u0d14\0\u0d52\0\u0d90"+
    "\0\u0dce\0\u0e0c\0\u0e4a\0\u02e8\0\u0e88\0\u0ec6\0\u0f04\0\u0f42"+
    "\0\u0f80\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132"+
    "\0\76\0\76\0\u087a\0\76\0\u1170\0\u11ae\0\u11ec\0\u122a"+
    "\0\u02e8\0\u02e8\0\u02e8\0\u1268\0\u12a6\0\u12e4\0\u1322\0\u1360"+
    "\0\u139e\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512\0\u02e8"+
    "\0\u1550\0\u158e\0\u15cc\0\u160a\0\u02e8\0\u1648\0\u1686\0\u16c4"+
    "\0\u1702\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u1838\0\u1876\0\u18b4"+
    "\0\u18f2\0\u02e8\0\u1930\0\u10f4\0\u196e\0\u19ac\0\u19ea\0\u1a28"+
    "\0\u1a66\0\u02e8\0\u1aa4\0\u1ae2\0\u1b20\0\u1b5e\0\u1b9c\0\u02e8"+
    "\0\u1bda\0\u1c18\0\u1c56\0\u02e8\0\u1c94\0\u02e8\0\u1cd2\0\u1d10"+
    "\0\u1d4e\0\u1d8c\0\u1dca\0\u1e08\0\u1e46\0\u1e84\0\u1ec2\0\u1f00"+
    "\0\u02e8\0\u02e8\0\u1f3e\0\u02e8\0\u1f7c\0\u1fba\0\u1ff8\0\u02e8"+
    "\0\u2036\0\u2074\0\u02e8\0\u20b2\0\u02e8\0\u20f0\0\u212e\0\u02e8"+
    "\0\u216c\0\u21aa\0\u02e8\0\u21e8\0\u2226\0\u2264\0\u02e8\0\u02e8"+
    "\0\u22a2\0\u22e0\0\u231e\0\u235c\0\u02e8\0\u239a\0\u23d8\0\u02e8"+
    "\0\u2416\0\u2454\0\u2492\0\u24d0\0\u250e\0\u254c\0\u258a\0\u25c8"+
    "\0\u2606\0\u2644\0\u02e8\0\u02e8\0\u2682\0\u26c0\0\u02e8\0\u02e8"+
    "\0\u02e8\0\u26fe\0\u273c\0\u02e8\0\u277a\0\76\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\76\0\u27b8\0\u02e8\0\u27f6\0\u2834\0\u02e8\0\u02e8\0\u2872"+
    "\0\u28b0\0\u28ee\0\76\0\u02e8\0\u02e8\0\u292c\0\u296a\0\u02e8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[256];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\3\1\5\1\6\1\7"+
    "\1\2\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\11\21\1\22\1\23\1\24\6\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\2\25"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\25\1\47\2\25\1\50\1\51\100\0\1\3"+
    "\73\0\2\52\1\3\1\52\1\4\10\52\1\53\60\52"+
    "\10\0\1\7\66\0\2\54\1\0\2\54\2\0\1\55"+
    "\1\0\1\56\10\0\11\57\3\0\7\57\1\0\25\57"+
    "\23\0\1\60\1\0\11\61\57\0\1\62\67\0\3\63"+
    "\1\0\2\63\1\0\3\63\1\64\1\63\11\21\42\63"+
    "\35\0\1\65\75\0\1\66\75\0\1\67\63\0\11\25"+
    "\3\0\7\25\1\0\25\25\25\0\11\25\3\0\2\25"+
    "\1\70\1\25\1\71\2\25\1\0\25\25\50\0\1\27"+
    "\52\0\11\25\3\0\7\25\1\0\13\25\1\72\11\25"+
    "\25\0\11\25\3\0\7\25\1\0\4\25\1\73\7\25"+
    "\1\74\4\25\1\75\3\25\25\0\11\25\3\0\7\25"+
    "\1\0\1\76\13\25\1\77\10\25\25\0\11\25\3\0"+
    "\7\25\1\0\4\25\1\100\3\25\1\101\14\25\25\0"+
    "\11\25\3\0\7\25\1\0\11\25\1\102\13\25\25\0"+
    "\11\25\3\0\7\25\1\0\1\103\20\25\1\104\3\25"+
    "\25\0\11\25\3\0\7\25\1\0\5\25\1\105\5\25"+
    "\1\106\11\25\25\0\11\25\3\0\7\25\1\0\10\25"+
    "\1\107\3\25\1\110\10\25\25\0\11\25\3\0\7\25"+
    "\1\0\14\25\1\111\10\25\25\0\11\25\3\0\7\25"+
    "\1\0\14\25\1\112\10\25\25\0\11\25\3\0\7\25"+
    "\1\0\15\25\1\113\1\114\6\25\25\0\11\25\3\0"+
    "\7\25\1\0\14\25\1\115\1\25\1\116\6\25\25\0"+
    "\11\25\3\0\7\25\1\0\4\25\1\117\20\25\25\0"+
    "\11\25\3\0\7\25\1\0\20\25\1\120\4\25\25\0"+
    "\11\25\3\0\7\25\1\0\4\25\1\121\3\25\1\122"+
    "\5\25\1\123\2\25\1\124\3\25\25\0\11\25\3\0"+
    "\7\25\1\0\1\125\24\25\2\0\2\52\1\3\1\52"+
    "\1\4\71\52\2\126\1\127\1\126\1\130\10\126\1\52"+
    "\60\126\1\0\2\54\1\0\2\54\4\0\1\131\70\0"+
    "\1\55\1\0\3\55\1\132\2\55\1\0\60\55\12\0"+
    "\1\133\70\0\1\57\1\0\1\57\1\55\1\57\1\134"+
    "\2\57\1\0\60\57\7\0\3\135\1\0\2\135\1\0"+
    "\5\135\11\61\42\135\15\0\1\136\67\0\3\63\1\0"+
    "\2\63\1\0\3\63\1\137\54\63\7\0\3\63\1\0"+
    "\2\63\1\0\3\63\1\137\1\63\11\140\42\63\23\0"+
    "\11\25\3\0\3\25\1\141\3\25\1\0\25\25\25\0"+
    "\11\25\3\0\3\25\1\142\3\25\1\0\25\25\25\0"+
    "\11\25\3\0\7\25\1\0\3\25\1\143\21\25\25\0"+
    "\11\25\3\0\7\25\1\0\6\25\1\144\16\25\25\0"+
    "\11\25\3\0\7\25\1\0\14\25\1\145\10\25\25\0"+
    "\11\25\3\0\7\25\1\0\20\25\1\146\4\25\25\0"+
    "\11\25\3\0\7\25\1\0\11\25\1\147\13\25\25\0"+
    "\11\25\3\0\7\25\1\0\13\25\1\150\11\25\25\0"+
    "\11\25\3\0\7\25\1\0\2\25\1\151\3\25\1\152"+
    "\2\25\1\153\13\25\25\0\11\25\3\0\7\25\1\0"+
    "\17\25\1\154\5\25\25\0\11\25\3\0\7\25\1\0"+
    "\17\25\1\155\5\25\25\0\11\25\3\0\7\25\1\0"+
    "\11\25\1\156\13\25\25\0\11\25\3\0\7\25\1\0"+
    "\13\25\1\157\11\25\25\0\11\25\3\0\7\25\1\0"+
    "\20\25\1\160\4\25\25\0\11\25\3\0\7\25\1\0"+
    "\6\25\1\161\16\25\25\0\11\25\3\0\7\25\1\0"+
    "\14\25\1\162\10\25\25\0\11\25\3\0\7\25\1\0"+
    "\20\25\1\163\1\25\1\164\2\25\25\0\11\25\3\0"+
    "\7\25\1\0\20\25\1\165\4\25\25\0\11\25\3\0"+
    "\7\25\1\0\4\25\1\166\20\25\25\0\11\25\3\0"+
    "\7\25\1\0\16\25\1\167\6\25\25\0\11\25\3\0"+
    "\7\25\1\0\10\25\1\170\3\25\1\171\10\25\25\0"+
    "\11\25\3\0\7\25\1\0\17\25\1\172\1\173\4\25"+
    "\25\0\11\25\3\0\7\25\1\0\1\174\15\25\1\175"+
    "\6\25\25\0\11\25\3\0\7\25\1\0\12\25\1\176"+
    "\12\25\25\0\11\25\3\0\7\25\1\0\12\25\1\177"+
    "\12\25\25\0\11\25\3\0\7\25\1\0\21\25\1\200"+
    "\3\25\25\0\11\25\3\0\7\25\1\0\16\25\1\201"+
    "\6\25\25\0\11\25\3\0\7\25\1\0\16\25\1\202"+
    "\6\25\2\0\2\126\1\127\1\126\1\130\10\126\1\203"+
    "\60\126\15\204\1\205\62\204\1\127\12\204\1\205\60\204"+
    "\7\0\3\135\1\0\2\135\1\0\60\135\15\0\1\136"+
    "\4\0\1\3\62\0\3\63\1\0\2\63\1\0\3\63"+
    "\1\137\1\63\11\206\42\63\7\0\3\206\1\0\2\206"+
    "\1\0\5\206\11\140\42\206\23\0\11\25\3\0\7\25"+
    "\1\0\10\25\1\207\14\25\25\0\11\25\3\0\7\25"+
    "\1\0\11\25\1\210\13\25\25\0\11\25\3\0\7\25"+
    "\1\0\20\25\1\211\4\25\25\0\11\25\3\0\7\25"+
    "\1\0\11\25\1\212\13\25\25\0\11\25\3\0\7\25"+
    "\1\0\17\25\1\213\5\25\25\0\11\25\3\0\7\25"+
    "\1\0\10\25\1\214\14\25\25\0\11\25\3\0\7\25"+
    "\1\0\16\25\1\215\6\25\25\0\11\25\3\0\7\25"+
    "\1\0\1\216\24\25\25\0\11\25\3\0\7\25\1\0"+
    "\20\25\1\217\4\25\25\0\11\25\3\0\7\25\1\0"+
    "\4\25\1\220\20\25\25\0\11\25\3\0\7\25\1\0"+
    "\17\25\1\221\5\25\25\0\11\25\3\0\7\25\1\0"+
    "\2\25\1\222\22\25\25\0\11\25\3\0\7\25\1\0"+
    "\20\25\1\223\4\25\25\0\11\25\3\0\7\25\1\0"+
    "\15\25\1\224\7\25\25\0\11\25\3\0\7\25\1\0"+
    "\14\25\1\225\10\25\25\0\11\25\3\0\7\25\1\0"+
    "\4\25\1\226\20\25\25\0\11\25\3\0\7\25\1\0"+
    "\16\25\1\227\6\25\25\0\11\25\3\0\7\25\1\0"+
    "\20\25\1\230\4\25\25\0\11\25\3\0\7\25\1\0"+
    "\13\25\1\231\11\25\25\0\11\25\3\0\7\25\1\0"+
    "\23\25\1\232\1\25\25\0\11\25\3\0\7\25\1\0"+
    "\20\25\1\233\4\25\25\0\11\25\3\0\7\25\1\0"+
    "\21\25\1\234\3\25\25\0\11\25\3\0\7\25\1\0"+
    "\16\25\1\235\1\25\1\236\4\25\25\0\11\25\3\0"+
    "\7\25\1\0\10\25\1\237\14\25\25\0\11\25\3\0"+
    "\7\25\1\0\15\25\1\240\7\25\25\0\11\25\3\0"+
    "\7\25\1\0\4\25\1\241\20\25\25\0\11\25\3\0"+
    "\7\25\1\0\4\25\1\242\20\25\25\0\11\25\3\0"+
    "\7\25\1\0\13\25\1\243\11\25\2\0\2\126\1\127"+
    "\1\126\1\130\10\126\1\203\4\126\1\52\53\126\15\204"+
    "\1\205\4\204\1\3\53\204\7\0\3\206\1\0\2\206"+
    "\1\0\60\206\23\0\11\25\3\0\7\25\1\0\13\25"+
    "\1\244\11\25\25\0\11\25\3\0\7\25\1\0\4\25"+
    "\1\245\20\25\25\0\11\25\3\0\7\25\1\0\14\25"+
    "\1\246\10\25\25\0\11\25\3\0\7\25\1\0\14\25"+
    "\1\247\3\25\1\250\4\25\25\0\11\25\3\0\7\25"+
    "\1\0\12\25\1\251\12\25\25\0\11\25\3\0\7\25"+
    "\1\0\4\25\1\252\20\25\25\0\11\25\3\0\7\25"+
    "\1\0\24\25\1\253\25\0\11\25\3\0\7\25\1\0"+
    "\1\254\24\25\25\0\11\25\3\0\7\25\1\0\4\25"+
    "\1\255\20\25\25\0\11\25\3\0\7\25\1\0\20\25"+
    "\1\256\4\25\25\0\11\25\3\0\7\25\1\0\7\25"+
    "\1\257\15\25\25\0\11\25\3\0\7\25\1\0\16\25"+
    "\1\260\6\25\25\0\11\25\3\0\7\25\1\0\1\261"+
    "\24\25\25\0\11\25\3\0\7\25\1\262\25\25\25\0"+
    "\11\25\3\0\7\25\1\0\20\25\1\263\4\25\25\0"+
    "\11\25\3\0\7\25\1\0\10\25\1\264\14\25\25\0"+
    "\11\25\3\0\7\25\1\0\1\265\24\25\25\0\11\25"+
    "\3\0\7\25\1\0\16\25\1\266\6\25\25\0\11\25"+
    "\3\0\7\25\1\0\20\25\1\267\4\25\25\0\11\25"+
    "\3\0\7\25\1\0\4\25\1\270\20\25\25\0\11\25"+
    "\3\0\7\25\1\0\13\25\1\271\11\25\25\0\11\25"+
    "\3\0\7\25\1\0\4\25\1\272\20\25\25\0\11\25"+
    "\3\0\7\25\1\273\25\25\25\0\11\25\3\0\7\25"+
    "\1\0\1\274\24\25\25\0\11\25\3\0\7\25\1\0"+
    "\13\25\1\275\11\25\25\0\11\25\3\0\7\25\1\0"+
    "\11\25\1\276\13\25\25\0\11\25\3\0\7\25\1\0"+
    "\1\277\24\25\25\0\11\25\3\0\7\25\1\0\4\25"+
    "\1\300\20\25\25\0\11\25\3\0\7\25\1\0\13\25"+
    "\1\301\11\25\25\0\11\25\3\0\7\25\1\0\10\25"+
    "\1\302\14\25\25\0\11\25\3\0\7\25\1\0\4\25"+
    "\1\303\20\25\25\0\11\25\3\0\7\25\1\0\20\25"+
    "\1\304\4\25\41\0\1\305\1\306\1\307\1\310\56\0"+
    "\11\25\3\0\7\25\1\0\12\25\1\311\12\25\25\0"+
    "\11\25\3\0\7\25\1\0\16\25\1\312\6\25\25\0"+
    "\11\25\3\0\7\25\1\0\13\25\1\313\11\25\25\0"+
    "\11\25\3\0\7\25\1\0\6\25\1\314\16\25\25\0"+
    "\11\25\3\0\7\25\1\0\16\25\1\315\6\25\65\0"+
    "\1\316\35\0\11\25\3\0\7\25\1\0\13\25\1\317"+
    "\11\25\25\0\11\25\3\0\7\25\1\0\4\25\1\320"+
    "\20\25\25\0\11\25\3\0\7\25\1\0\11\25\1\321"+
    "\13\25\25\0\11\25\3\0\7\25\1\0\2\25\1\322"+
    "\22\25\25\0\11\25\3\0\7\25\1\0\14\25\1\323"+
    "\10\25\25\0\11\25\3\0\7\25\1\0\16\25\1\324"+
    "\6\25\25\0\11\25\3\0\7\25\1\0\10\25\1\325"+
    "\14\25\25\0\1\326\1\327\1\330\1\331\1\332\1\333"+
    "\70\0\1\334\1\335\1\336\1\337\1\340\1\341\1\342"+
    "\1\343\70\0\1\344\1\345\1\346\1\347\1\350\1\351"+
    "\66\0\1\352\1\353\1\354\1\355\1\356\1\357\1\360"+
    "\1\361\66\0\11\25\3\0\7\25\1\0\10\25\1\362"+
    "\14\25\25\0\11\25\3\0\7\25\1\0\20\25\1\363"+
    "\4\25\25\0\11\25\3\0\7\25\1\0\1\364\24\25"+
    "\56\0\1\365\44\0\11\25\3\0\7\25\1\0\4\25"+
    "\1\366\20\25\25\0\11\25\3\0\7\25\1\0\13\25"+
    "\1\367\11\25\25\0\11\25\3\0\7\25\1\0\14\25"+
    "\1\370\10\25\25\0\11\25\3\0\7\25\1\0\20\25"+
    "\1\371\4\25\25\0\11\25\3\0\7\25\1\0\20\25"+
    "\1\372\4\25\56\0\1\373\44\0\11\25\3\0\7\25"+
    "\1\0\13\25\1\374\11\25\25\0\11\25\3\0\7\25"+
    "\1\0\24\25\1\375\25\0\11\25\3\0\7\25\1\0"+
    "\21\25\1\376\3\25\25\0\11\25\3\0\7\25\1\0"+
    "\16\25\1\377\6\25\25\0\11\25\3\0\7\25\1\0"+
    "\4\25\1\u0100\20\25\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10664];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\3\1\6\11\31\1\2\11"+
    "\2\1\2\0\1\1\2\0\1\1\1\0\2\1\3\11"+
    "\41\1\2\11\1\1\1\11\1\1\1\0\45\1\2\0"+
    "\54\1\1\0\10\1\1\0\11\1\4\0\5\1\1\0"+
    "\7\1\34\11\3\1\1\0\5\1\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[256];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "Error_léxico_X", yyline, yycolumn);
            }
            // fall through
          case 99: break;
          case 2:
            { /*Ignorar*/
            }
            // fall through
          case 100: break;
          case 3:
            { return token(yytext(), "FIN_DE_LINEA", yyline, yycolumn);
            }
            // fall through
          case 101: break;
          case 4:
            { return token(yytext(), "Error_léxico_0", yyline, yycolumn);
            }
            // fall through
          case 102: break;
          case 5:
            { return token(yytext(), "Error_léxico_3", yyline, yycolumn);
            }
            // fall through
          case 103: break;
          case 6:
            { return token(yytext(), "SIGNO_AGRUPACION_3", yyline, yycolumn);
            }
            // fall through
          case 104: break;
          case 7:
            { return token(yytext(), "SIGNO_AGRUPACION_4", yyline, yycolumn);
            }
            // fall through
          case 105: break;
          case 8:
            { return token(yytext(), "OPERADOR_ARITMETICO_3", yyline, yycolumn);
            }
            // fall through
          case 106: break;
          case 9:
            { return token(yytext(), "OPERADOR_ARITMETICO_1", yyline, yycolumn);
            }
            // fall through
          case 107: break;
          case 10:
            { return token(yytext(), "SIGNO_PUNTUACION_1", yyline, yycolumn);
            }
            // fall through
          case 108: break;
          case 11:
            { return token(yytext(), "OPERADOR_ARITMETICO_2", yyline, yycolumn);
            }
            // fall through
          case 109: break;
          case 12:
            { return token(yytext(), "SIGNO_PUNTUACION_2", yyline, yycolumn);
            }
            // fall through
          case 110: break;
          case 13:
            { return token(yytext(), "OPERADOR_ARITMETICO_4", yyline, yycolumn);
            }
            // fall through
          case 111: break;
          case 14:
            { return token(yytext(), "NUMERO_ENTERO", yyline, yycolumn);
            }
            // fall through
          case 112: break;
          case 15:
            { return token(yytext(), "OPERADOR_RELACIONAL_2", yyline, yycolumn);
            }
            // fall through
          case 113: break;
          case 16:
            { return token(yytext(), "OPERADOR_ASIGNACION", yyline, yycolumn);
            }
            // fall through
          case 114: break;
          case 17:
            { return token(yytext(), "OPERADOR_RELACIONAL_1", yyline, yycolumn);
            }
            // fall through
          case 115: break;
          case 18:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
            }
            // fall through
          case 116: break;
          case 19:
            { return token(yytext(), "Error_léxico_4", yyline, yycolumn);
            }
            // fall through
          case 117: break;
          case 20:
            { return token(yytext(), "SIGNO_AGRUPACION_1", yyline, yycolumn);
            }
            // fall through
          case 118: break;
          case 21:
            { return token(yytext(), "SIGNO_AGRUPACION_2", yyline, yycolumn);
            }
            // fall through
          case 119: break;
          case 22:
            { return token(yytext(), "Error_léxico_2", yyline, yycolumn);
            }
            // fall through
          case 120: break;
          case 23:
            { return token(yytext(), "Error_léxico_6", yyline, yycolumn);
            }
            // fall through
          case 121: break;
          case 24:
            { return token(yytext(), "Error_léxico_13", yyline, yycolumn);
            }
            // fall through
          case 122: break;
          case 25:
            { return token(yytext(), "Error_léxico_12", yyline, yycolumn);
            }
            // fall through
          case 123: break;
          case 26:
            { return token(yytext(), "OPERADOR_RELACIONAL_4", yyline, yycolumn);
            }
            // fall through
          case 124: break;
          case 27:
            { return token(yytext(), "OPERADOR_RELACIONAL_5", yyline, yycolumn);
            }
            // fall through
          case 125: break;
          case 28:
            { return token(yytext(), "OPERADOR_RELACIONAL_3", yyline, yycolumn);
            }
            // fall through
          case 126: break;
          case 29:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_4", yyline, yycolumn);
            }
            // fall through
          case 127: break;
          case 30:
            { return token(yytext(), "OPERADOR_LOGICO_2", yyline, yycolumn);
            }
            // fall through
          case 128: break;
          case 31:
            { return token(yytext(), "Error_léxico_1", yyline, yycolumn);
            }
            // fall through
          case 129: break;
          case 32:
            { return token(yytext(), "IDENTIFICADOR_CADENA", yyline, yycolumn);
            }
            // fall through
          case 130: break;
          case 33:
            { return token(yytext(), "Error_léxico_7", yyline, yycolumn);
            }
            // fall through
          case 131: break;
          case 34:
            { return token(yytext(), "NUMERO_REAL", yyline, yycolumn);
            }
            // fall through
          case 132: break;
          case 35:
            { return token(yytext(), "TIPO_PUERTO_4", yyline, yycolumn);
            }
            // fall through
          case 133: break;
          case 36:
            { return token(yytext(), "TIPO_PUERTO_3", yyline, yycolumn);
            }
            // fall through
          case 134: break;
          case 37:
            { return token(yytext(), "OPERADOR_LOGICO_1", yyline, yycolumn);
            }
            // fall through
          case 135: break;
          case 38:
            { return token(yytext(), "TIPO_DATO_1", yyline, yycolumn);
            }
            // fall through
          case 136: break;
          case 39:
            { return token(yytext(), "OPERADOR_LOGICO_3", yyline, yycolumn);
            }
            // fall through
          case 137: break;
          case 40:
            { return token(yytext(), "DECLARACION_1", yyline, yycolumn);
            }
            // fall through
          case 138: break;
          case 41:
            { return token(yytext(), "Error_léxico_5", yyline, yycolumn);
            }
            // fall through
          case 139: break;
          case 42:
            { return token(yytext(), "PALABRA_RESERVADA_4", yyline, yycolumn);
            }
            // fall through
          case 140: break;
          case 43:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_5", yyline, yycolumn);
            }
            // fall through
          case 141: break;
          case 44:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_3", yyline, yycolumn);
            }
            // fall through
          case 142: break;
          case 45:
            { return token(yytext(), "MOTOR_1", yyline, yycolumn);
            }
            // fall through
          case 143: break;
          case 46:
            { return token(yytext(), "METODO_SENSOR_3", yyline, yycolumn);
            }
            // fall through
          case 144: break;
          case 47:
            { return token(yytext(), "CONDICIONAL_1", yyline, yycolumn);
            }
            // fall through
          case 145: break;
          case 48:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_2", yyline, yycolumn);
            }
            // fall through
          case 146: break;
          case 49:
            { return token(yytext(), "DECLARACION_2", yyline, yycolumn);
            }
            // fall through
          case 147: break;
          case 50:
            { return token(yytext(), "PALABRA_RESERVADA_2", yyline, yycolumn);
            }
            // fall through
          case 148: break;
          case 51:
            { return token(yytext(), "CONDICIONAL_2", yyline, yycolumn);
            }
            // fall through
          case 149: break;
          case 52:
            { return token(yytext(), "TIPO_PUERTO_6", yyline, yycolumn);
            }
            // fall through
          case 150: break;
          case 53:
            { return token(yytext(), "PALABRA_RESERVADA_6", yyline, yycolumn);
            }
            // fall through
          case 151: break;
          case 54:
            { return token(yytext(), "MOTOR_3", yyline, yycolumn);
            }
            // fall through
          case 152: break;
          case 55:
            { return token(yytext(), "METODO_SENSOR_2", yyline, yycolumn);
            }
            // fall through
          case 153: break;
          case 56:
            { return token(yytext(), "TIPO_PUERTO_5", yyline, yycolumn);
            }
            // fall through
          case 154: break;
          case 57:
            { return token(yytext(), "METODO_SENSOR_4", yyline, yycolumn);
            }
            // fall through
          case 155: break;
          case 58:
            { return token(yytext(), "PALABRA_RESERVADA_5", yyline, yycolumn);
            }
            // fall through
          case 156: break;
          case 59:
            { return token(yytext(), "TIPO_DATO_2", yyline, yycolumn);
            }
            // fall through
          case 157: break;
          case 60:
            { return token(yytext(), "TIPO_DATO_4", yyline, yycolumn);
            }
            // fall through
          case 158: break;
          case 61:
            { return token(yytext(), "PALABRA_RESERVADA_7", yyline, yycolumn);
            }
            // fall through
          case 159: break;
          case 62:
            { return token(yytext(), "TIPO_DATO_3", yyline, yycolumn);
            }
            // fall through
          case 160: break;
          case 63:
            { return token(yytext(), "PALABRA_RESERVADA_1", yyline, yycolumn);
            }
            // fall through
          case 161: break;
          case 64:
            { return token(yytext(), "PUERTO_1", yyline, yycolumn);
            }
            // fall through
          case 162: break;
          case 65:
            { return token(yytext(), "PUERTO_2", yyline, yycolumn);
            }
            // fall through
          case 163: break;
          case 66:
            { return token(yytext(), "PUERTO_3", yyline, yycolumn);
            }
            // fall through
          case 164: break;
          case 67:
            { return token(yytext(), "PUERTO_4", yyline, yycolumn);
            }
            // fall through
          case 165: break;
          case 68:
            { return token(yytext(), "PUERTO_5", yyline, yycolumn);
            }
            // fall through
          case 166: break;
          case 69:
            { return token(yytext(), "PUERTO_6", yyline, yycolumn);
            }
            // fall through
          case 167: break;
          case 70:
            { return token(yytext(), "PUERTO_7", yyline, yycolumn);
            }
            // fall through
          case 168: break;
          case 71:
            { return token(yytext(), "PUERTO_8", yyline, yycolumn);
            }
            // fall through
          case 169: break;
          case 72:
            { return token(yytext(), "PUERTO_9", yyline, yycolumn);
            }
            // fall through
          case 170: break;
          case 73:
            { return token(yytext(), "PUERTO_10", yyline, yycolumn);
            }
            // fall through
          case 171: break;
          case 74:
            { return token(yytext(), "PUERTO_11", yyline, yycolumn);
            }
            // fall through
          case 172: break;
          case 75:
            { return token(yytext(), "PUERTO_12", yyline, yycolumn);
            }
            // fall through
          case 173: break;
          case 76:
            { return token(yytext(), "PUERTO_13", yyline, yycolumn);
            }
            // fall through
          case 174: break;
          case 77:
            { return token(yytext(), "PUERTO_14", yyline, yycolumn);
            }
            // fall through
          case 175: break;
          case 78:
            { return token(yytext(), "PUERTO_15", yyline, yycolumn);
            }
            // fall through
          case 176: break;
          case 79:
            { return token(yytext(), "PUERTO_16", yyline, yycolumn);
            }
            // fall through
          case 177: break;
          case 80:
            { return token(yytext(), "PUERTO_17", yyline, yycolumn);
            }
            // fall through
          case 178: break;
          case 81:
            { return token(yytext(), "PUERTO_18", yyline, yycolumn);
            }
            // fall through
          case 179: break;
          case 82:
            { return token(yytext(), "PUERTO_19", yyline, yycolumn);
            }
            // fall through
          case 180: break;
          case 83:
            { return token(yytext(), "PUERTO_20", yyline, yycolumn);
            }
            // fall through
          case 181: break;
          case 84:
            { return token(yytext(), "PUERTO_21", yyline, yycolumn);
            }
            // fall through
          case 182: break;
          case 85:
            { return token(yytext(), "PUERTO_22", yyline, yycolumn);
            }
            // fall through
          case 183: break;
          case 86:
            { return token(yytext(), "PUERTO_23", yyline, yycolumn);
            }
            // fall through
          case 184: break;
          case 87:
            { return token(yytext(), "PUERTO_24", yyline, yycolumn);
            }
            // fall through
          case 185: break;
          case 88:
            { return token(yytext(), "PUERTO_25", yyline, yycolumn);
            }
            // fall through
          case 186: break;
          case 89:
            { return token(yytext(), "PUERTO_26", yyline, yycolumn);
            }
            // fall through
          case 187: break;
          case 90:
            { return token(yytext(), "PUERTO_27", yyline, yycolumn);
            }
            // fall through
          case 188: break;
          case 91:
            { return token(yytext(), "PUERTO_28", yyline, yycolumn);
            }
            // fall through
          case 189: break;
          case 92:
            { return token(yytext(), "MOTOR_2", yyline, yycolumn);
            }
            // fall through
          case 190: break;
          case 93:
            { return token(yytext(), "METODO_SENSOR_1", yyline, yycolumn);
            }
            // fall through
          case 191: break;
          case 94:
            { return token(yytext(), "ESTRUCTURA_DE_CONTROL_1", yyline, yycolumn);
            }
            // fall through
          case 192: break;
          case 95:
            { return token(yytext(), "PALABRA_RESERVADA_8", yyline, yycolumn);
            }
            // fall through
          case 193: break;
          case 96:
            { return token(yytext(), "PALABRA_RESERVADA_3", yyline, yycolumn);
            }
            // fall through
          case 194: break;
          case 97:
            { return token(yytext(), "TIPO_PUERTO_1", yyline, yycolumn);
            }
            // fall through
          case 195: break;
          case 98:
            { return token(yytext(), "TIPO_PUERTO_2", yyline, yycolumn);
            }
            // fall through
          case 196: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
